# Generated by Django 4.1.4 on 2023-01-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='password',
            new_name='passs',
        ),
    ]
