# Generated by Django 4.1.4 on 2023-01-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_passs_userdetails_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
    ]
